carts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^idnex/', views.index, name='index'),
    url(r'^add_goods/', views.add_goods, name='add_goods'),
    url(r'^remove_goods/', views.remove_goods, name='remove_goods'),
    url(r'^edit_goods_num/', views.edit_goods_num, name='edit_goods_num'),

]

users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^index/$', views.index, name='index'),
    url(r'^order/$', views.order, name='order'),
    url(r'^site/$', views.site, name='site'),
    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^check_register_username/$', views.check_register_username, name='check_register_username'),
    url(r'^login_handle/$', views.login_handle, name='login_handle'),
    url(r'^logout_handle/$', views.logout_handle, name='logout_handle'),
    url(r'^address_edit/$', views.address_edit, name='address_edit'),

]

order/models.py
from django.db import models
from db.BaseModel import *


# Create your models here.
class GoodsDetail(BaseModel):
    """订单商品详情信息表"""
    # 商品名称
    detail_name = models.CharField(max_length=50)
    # 商品价格
    detail_price = models.IntegerField()
    # 商品数量
    detail_amount = models.IntegerField()
    # 商品单位
    detail_unit = models.CharField(max_length=100)
    # 商品图片
    detail_img = models.ImageField()
    # 商品ID
    detail_goodsid = models.IntegerField()
    # 订单商品列表
    detail_goods = models.ForeignKey('Order')

class Order(BaseModel):
    """订单基本信息模型"""
    status = (
        (1, '待付款'),
        (2, '待发货'),
        (3, '待收货'),
        (4, '已完成'),
    )

    pay = (
        (1, '货到付款'),
        (2, '微信支付'),
        (3, '支付宝支付'),
        (4, '银联支付'),
    )

    # 订单编号
    order_number = models.CharField(max_length=50)
    # 收货地址
    order_addr = models.CharField(max_length=100)
    # 收货人
    order_recv = models.CharField(max_length=10)
    # 运费
    order_fee = models.IntegerField(default=10)
    # 订单状态
    order_status = models.SmallIntegerField(choices=status, default=1)
    # 支付方式
    order_pay = models.SmallIntegerField(choices=pay, default=1)
    # 订单所属用户
    order_user = models.ForeignKey('users.User')

users/models.py
from django.db import models
from db.BaseModel import *
from utils.tool_fun import *

"""
Create your models here.
项目正式开始 201710242122
先分析页面 寻找需要维护的数据，用来建模（这是很重要的一个步骤）
先建个基类模型类（因为其他应用都能用得着的字段属性，比如更新时间，添加时间，）

"""

class UserManager(models.Manager):
    """用户信息自定义管理器类"""
    # 用过用户名查找该对应数据是否在数据库的表中
    def user_by_name(self, username):
        try:
            return self.get(user_name=username)
        except User.DoesNotExist:
            return None

    # 将成功注册的用户信息数据保存到数据库中
    def register_data_2_db(self, request):
        user = self.model()
        user.user_name = post(request, 'user_name')
        user.user_mail = post(request, 'user_mail')
        user.user_pass = password_encrypt(post(request, 'user_pass1'))
        user.save()

    # 将用户中心地址也的数据更新（修改）到userbiao中
    def update_user_info(self, request):
        user = self.user_by_name(get_session(request, 'username'))
        user.user_recv = post(request, 'user_recv')
        user.user_addr = post(request, 'user_addr')
        user.user_mail = post(request, 'user_mail')
        user.user_tele = post(request, 'user_tele')
        user.save()


class User(BaseModel):
    """用户信息模型类"""
    # 用户名
    user_name = models.CharField(max_length=20)
    # 用户密码
    user_pass = models.CharField(max_length=100)
    # 用户密码
    user_mail = models.CharField(max_length=50)
    # 用户地址(收件地址)
    user_addr = models.CharField(max_length=50)
    # 用户手机
    user_tele = models.CharField(max_length=11)
    # 邮政编码
    user_code = models.CharField(max_length=10)
    # 收件人姓名
    user_recv = models.CharField(max_length=20, default='')
    # 创建自定义管理器类
    objects = UserManager()


# 用户浏览商品详情页面的记录，另外创建一个表，记录相关数据
class RecordBrowse(BaseModel):

    # 浏览商品详情页面
    browse_goods = models.ForeignKey('goods.GoodsInfo')
    # 浏览者
    browse_user = models.ForeignKey('User')

users/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from .models import *
from .functions import *
from django.http import JsonResponse
from order.models import *
from django.core.paginator import Paginator
# Create your views here.

def login(request):
    """登录页"""

    return render(request, 'users/login.html', locals())

def register(request):
    """注册页"""
    mess = get_messages(request)
    return render(request, 'users/register.html', locals())

@check_permission
def index(request):
    """用户中心首页"""
    user = User.objects.user_by_name(get_session(request, 'username'))
    # print('user_name',user.user_name)
    return render(request, 'users/user_center_info.html', locals())

@check_permission
def order(request):
    """订单中心首页"""
    # 创建订单中心数据
    # 创建订单基本信息数据对象
    orders = Order.objects.filter(order_user_id=get_session(request, 'uid'))

    # (创建分页器对象)分页显示
    paginator = Paginator(orders, 2)
    # 获取当前分页
    current_page = get(request, 'page')
    if not current_page:
        current_page = 1
    orders = paginator.page(current_page)
    for order in orders:
        order.total = 0
        for goods in order.goodsdetail_set.all():
            order.total += goods.detail_amount * goods.detail_price

    return render(request, 'users/user_center_order.html', locals())

@check_permission
def site(request):
    """收货地址信息页"""
    user = User.objects.user_by_name(get_session(request, 'username'))
    return render(request, 'users/user_center_site.html', locals())

# -------------start----------
# 创建好模型类，接下来从注册开始下手。如何下手？先去看看页面源码。
# 前端客户传过来的数据永远不可信，前端做的简单js验证，只要跟数据库有关我们后端必须对传来的数据进行验证
# 后端验证，怎么验证？这就涉及到前端是通过何种方式把数据传过来的，但是不管是哪种方式，数据验证/处理视图函数肯定是有的
def register_handle(request):
    # 发送来了数据，需要先进行验证
    if check_register_data(request):
        # 用户信息入库
        User.objects.register_data_2_db(request)
        return redirect(reverse('users:login'))
    else:
        return redirect(reverse('users:register'))

# 接受来自register-js，中的ajax对用户名的校验函数的请求，需返回JSON数据
def check_register_username(request):
    if user_is_exist(request):
        return JsonResponse({'ret':1})
    else:
        return JsonResponse({'ret':0})
# ---------------------------------register-end--
# login
# 登录信息校验/处理
def login_handle(request):
    # 先进行简单的验证
    if check_login_data(request):
        # 1.记录用户登录状态（写session）
        keep_user_online(request)
        # 2.是否记住用户名（写cokie）
        response = redirect(reverse('users:index'))
        remember_username(request, response)
        return response
    else:
        return redirect(reverse('users:login'))

# 注销处理函数
def logout_handle(request):
    # 这里还有个先保存上一页，放在后面在去做（原因：现在不想去改模板中的图片链接，不改的话，现在加个记录上一页的中间件会记录图片请求的url
    # 这样就会影响我的进度）
    del_session(request)
    return redirect(reverse('goods:index'))

# 接下来处理user_center_site.html页面中的修改地址的功能。
# 因为设计限制，只能在这修改当前用户信息表中的信息
def address_edit(request):
    # 先简单检测一下
    if check_address_edit_params(request):
        print('addrees')
        # 检测通过，更新user表中对应用户的数据
        User.objects.update_user_info(request)
    return redirect(reverse('users:site'))

templates/users/left_common_menu.html
        <div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'users:index' %}" {% if flag == 'info' %} class="active" {% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'users:order' %}" {% if flag == 'order' %} class="active" {% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'users:site' %}" {% if flag == 'site' %} class="active" {% endif %}>· 收货地址</a></li>
			</ul>
		</div>

templates/users/login.html
{% extends 'common/base.html' %}
{% load staticfiles %}

{% block body %}
<div class="login_top clearfix">
		<a href="{% url 'goods:index' %}" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'users:register' %}">立即注册</a>
				</div>
				<div class="form_input">

					<form method="post" action="{% url 'users:login_handle' %}">
                        {% csrf_token %}
						<input type="text" name="user_name" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="user_pass" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="user_memb">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>

				</div>
			</div>
		</div>
	</div>
{% endblock body %}

{% block footer_css %} no-mp{% endblock footer_css %}

templates/users/register.html
{% extends 'common/base.html' %}
{% load staticfiles %}
{% block header_js %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock header_js %}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'users:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">

				<form action="{% url 'users:register_handle' %}" method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
						<span class="error_tip_info">{{ mess.user_name }}</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="user_pass1" id="pwd">
						<span class="error_tip">提示信息</span>
						<span class="error_tip_info">{{ mess.user_pass }}</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="user_pass2" id="cpwd">
						<span class="error_tip">提示信息</span>
						<span class="error_tip_info">{{ mess.user_pass }}</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="user_mail" id="email">
						<span class="error_tip">提示信息</span>
						<span class="error_tip_info">{{ mess.user_mail }}</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="user_allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>

					<li class="reg_form">
						<input type="submit" value="注 册" name="" id="submit">
					</li>

				</ul>				
				</form>

			</div>

		</div>

	</div>
{% endblock body %}

{% block footer_css %} no-mp{% endblock footer_css %}

templates/users/user_center_info.html
{% extends 'common/base.html' %}
{% load staticfiles %}
{% load users_filters %}
{% block body %}

{#    包含了页头状态栏#}
	{% include 'common/status.html' %}

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>

        {#   包含搜索框#}
    {% include 'common/search.html' %}
    </div>

	<div class="main_con clearfix">

        {#包含用户中心信息左侧导航栏#}
		{% include 'users/left_common_menu.html' with flag='info' %}

		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.user_name }}</li>
							<li><span>联系方式：</span>{{ user.user_tele }}</li>
							<li><span>联系地址：</span>{{ user.user_addr }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">

                {% for record in user.recordbrowse_set.all|browse_sort %}
				<li>
					<a href="{% url 'goods:detail' %}?id={{ record.browse_goods.id }}"><img src="{% static record.browse_goods.goods_image %}"></a>
					<h4><a href="{% url 'goods:detail' %}?id={{ record.browse_goods.id }}">{{ record.browse_goods.goods_name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ record.browse_goods.goods_price }}</span>
						<span class="unit">{{ record.browse_goods.price }}/{{ record.browse_goods.goods_unit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}

			</ul>
		</div>
		</div>
	</div>
{% endblock body %}

templates/users/user_center_order.html
{% extends 'common/base.html' %}
{% load staticfiles %}


{% block body %}
{#    包含了页头状态栏#}
	{% include 'common/status.html' %}

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>

       {#   包含搜索框#}
    {% include 'common/search.html' %}

    </div>

	<div class="main_con clearfix">

        {#包含用户中心信息左侧导航栏#}
		{% include 'users/left_common_menu.html' with flag='order' %}
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
        {% for order in orders %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.update_time }}</li>
					<li class="col02">订单号：{{ order.order_number }}</li>
					<li class="col02 stress">
                        {% if order.order_status == 1 %}
                            货到付款
                        {% elif order.order_status == 2 %}
                            微信支付
                        {% elif order.order_status == 3 %}
                            支付宝支付
                        {% elif order.order_status == 4 %}
                            银联支付
                        {% endif %}
                    </li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for goods in order.goodsdetail_set.all %}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="{% static goods.detail_img %}"></li>
									<li class="col02">{{ goods.detail_name }}<em>{{ goods.detail_price }}元/{{ goods.detail_unit }}</em></li>
									<li class="col03">{{ goods.detail_amount }}</li>
									<li class="col04">{{ goods.detail_price }}元</li>
								</ul>
                                 {% endfor %}
							</td>
							<td width="15%">{{ order.total }}元</td>
                            <td width="15%">
                                {% if order.order_pay == 1 %}
                                    未支付
                                {% elif order.order_pay == 2 %}
                                    待发货
                                {% elif order.order_pay == 3 %}
                                    待收货
                                {% elif order.order_pay == 4 %}
                                    已完成
                                {% endif %}

                            </td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
        {% endfor %}
{#            已支付状态订单#}
{#				<ul class="order_list_th w978 clearfix">#}
{#					<li class="col01">2016-8-21 17:36:24</li>#}
{#					<li class="col02">订单号：56872934</li>#}
{#					<li class="col02 stress">已支付</li>			#}
{#				</ul>#}
{##}
{#            <table class="order_list_table w980">#}
{#                    <tbody>#}
{#						<tr>#}
{#							<td width="55%">#}
{#								<ul class="order_goods_list clearfix">					#}
{#									<li class="col01"><img src="images/goods02.jpg"></li>#}
{#									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	#}
{#									<li class="col03">1</li>#}
{#									<li class="col04">11.80元</li>	#}
{#								</ul>#}
{#								<ul class="order_goods_list clearfix">					#}
{#									<li class="col01"><img src="images/goods02.jpg"></li>#}
{#									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	#}
{#									<li class="col03">1</li>#}
{#									<li class="col04">11.80元</li>	#}
{#								</ul>#}
{#							</td>#}
{#							<td width="15%">33.60元</td>#}
{#							<td width="15%">已付款</td>#}
{#							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>#}
{#						</tr>#}
{#					</tbody>#}
{##}
{#				</table>#}


				<div class="pagenation">
                    {% if orders.has_previous %}
                    <a href="?page={{ orders.previous_page_number }}">上一页</a>
                    {% endif %}
                    {% for index in paginator.page_range %}
                        {% if index == orders.number %}
                            <a href="?page={{ index }}" class="active">{{ index }}</a>
                        {% else %}
                            <a href="?page={{ index }}">{{ index }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if orders.has_next %}
                    <a href="?page={{ orders.next_page_number }}">下一页></a>
                    {% endif %}
                </div>

		</div>
	</div>
{% endblock body %}

templates/users/user_center_site.html
{% extends 'common/base.html' %}
{% load staticfiles %}
{% block body %}

{#    包含了页头状态栏#}
	{% include 'common/status.html' %}

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>

{#   包含搜索框#}
    {% include 'common/search.html' %}

    </div>

	<div class="main_con clearfix">

        {#包含用户中心信息左侧导航栏#}
		{% include 'users/left_common_menu.html' with flag='site' %}

        <div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user.user_addr }}（{{ user.user_recv }} 收） {{ user.user_tele }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">

					<form action="{% url 'users:address_edit' %}" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="user_recv">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="user_addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="user_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="user_tele">
						</div>
						<input type="submit" name="" value="提交" class="info_submit">
					</form>

				</div>
		</div>
	</div>
{% endblock body %}